<a href="https://colab.research.google.com/github/VoidEnd315/Data-Science-and-NLP/blob/main/Label_and_onehot_Encoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing the libraries
import pandas as pd
import numpy as np

#reading the dataset
df=pd.read_csv("salary.csv")
df

Country  Age  Salary
0  United States   35   75000
1         Canada   28   60000
2          India   42   50000
3  United States   40   60500
4          Nepal   38   40000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Country  5 non-null      object
 1   Age      5 non-null      int64 
 2   Salary   5 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 248.0+ bytes


In [ ]:
#LabelEncoder
#converting Unique categorical variables into Unique numerical values
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['Country']=label_encoder.fit_transform(df['Country'])
df.head()

Country  Age  Salary
0        3   35   75000
1        0   28   60000
2        1   42   50000
3        3   40   60500
4        2   38   40000

In [ ]:
#OneHotEncoder
# It simply creates additional features based on the number of unique values in the categorical feature
df = pd.get_dummies(df, columns=['Country'], dtype='int')
df

Age  Salary  Country_Canada  Country_India  Country_Nepal  \
0   35   75000               0              0              0   
1   28   60000               1              0              0   
2   42   50000               0              1              0   
3   40   60500               0              0              0   
4   38   40000               0              0              1   

   Country_United States  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [7]:
# Initializing Input vector
class_vector =[2, 5, 6, 1, 4, 2, 3, 2]
print(class_vector)

# Applying the function on input class vector
from keras.utils import to_categorical
output_matrix = to_categorical(class_vector, num_classes = 7)

print(output_matrix)


[2, 5, 6, 1, 4, 2, 3, 2]
[[0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]]
